plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

title: Software and Board Games
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
page_gen:
  - data: learningbacklog.done
    name: title
    template: learning-backlog-item
    dir: learning-backlog/item
  - data: learningbacklog.investigating
    name: title
    template: learning-backlog-item
    dir: learning-backlog/item
  - data: learningbacklog.interested.next
    name: title
    template: learning-backlog-item
    dir: learning-backlog/item
  - data: learningbacklog.interested.possible
    name: title
    template: learning-backlog-item
    dir: learning-backlog/item
  - data: learningbacklog.interested.unranked
    name: title
    template: learning-backlog-item
    dir: learning-backlog/item